### ISSUE TITLE
Improve issue loading performance 

### ISSUE THREAD

**Issue by CaelumF** [CaelumF/edu-change#18]
Currently, issues are queried in their entirety and then iterated over by id to find a specific issue by id
With many issues, this will be a major slow down

- [x] Modify Issue.service.ts to query only issues by id and allow finding it to be handled by firebase server

- [x] Once fixed does anything rely on the old behaviour? change if so

**Comment by paranoidcake** [comment]
Fixed by @TooFiveFive in #19
